# title: Just the Docs Template
# description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs

# url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template


title: "Eye Tracking Guidelines"

email: 
description: >-
  This is an appendix for the paper How to Overcome Blinks in Eye Tracking for Interactive Systems at CHI.
  Authors:

# Eye Tracking Guidelines
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
search_enabled: true
# Build settings
remote_theme: pmarsceill/just-the-docs
#remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: minima
